### ISSUE TITLE
No deserialization in release build

### ISSUE THREAD

**Issue by k0zmo** [xomachine/NESM#10]
When building with -d:release all `assert()` calls are optimized out by the compiler. You should use `doAssert()` instead or move the calls to `stream.readData()` out of the `assert()` call

**Comment by xomachine** [comment]
Should be fixed by [3bd5929c](https://gitlab.com/xomachine/NESM/commit/3bd5929cdeba3f718d5a5b0539c15971a752db36)

**Comment by xomachine** [comment]
Merged to master
