### ISSUE TITLE
strange error which occurs only during nim doc; should docs work?

### ISSUE THREAD

**Issue by disruptek** [xomachine/NESM#13]
I'm trying to generate docs for https://github.com/disruptek/swayipc but things go haywire, seemingly as a result of nesm.  NESM works absolutely perfectly otherwise, so thanks for that!  :smile: 

My use of nesm seems pretty trivial to me; you can find it here:
https://github.com/disruptek/swayipc/blob/master/swayipc.nim#L260

This is the (first) error I get when I attempt to `nim doc swayipc.nim`:

```
/.nimble/pkgs/nesm-0.4.5/nesm/generator.nim(130, 12) Error: Type Header is not a basic type nor a complex type under 'serializable' block!
```

Things run right off the rails from there...

Any ideas?  Should I expect `nim doc` to work?

**Comment by xomachine** [comment]
Is it the only error that occurs during ```nim doc```? I tried to reproduce it and found a huge amount of other errors not related to NESM.
Another thing that I noticed, the ```nim doc``` ignores ```serializable``` macro and causes Non-intrusive serialization macros to be invoked which do not know about the Header type (becouse the ```serializable``` macro was ignored). So I think that the reason lies in brokenness of the ```nim doc``` rather than in NESM.

**Comment by disruptek** [comment]
That makes sense; the only warnings I get during normal compilation are from NESM, actually:

```
/home/adavidoff/.nimble/pkgs/nesm-0.4.5/nesm/procgen.nim(46, 7) Hint: 'size' is declared but not used [XDeclaredButNotUsed]
/home/adavidoff/.nimble/pkgs/nesm-0.4.5/nesm/procgen.nim(55, 3) Hint: 'serialize' is declared but not used [XDeclaredButNotUsed]
/home/adavidoff/.nimble/pkgs/nesm-0.4.5/nesm/procgen.nim(46, 7) Hint: 'size' is declared but not used [XDeclaredButNotUsed]
/home/adavidoff/.nimble/pkgs/nesm-0.4.5/nesm/procgen.nim(55, 3) Hint: 'serialize' is declared but not used [XDeclaredButNotUsed]
```
I'm a little curious about any other errors you got -- did you `nimble build` it? -- but I'll close this issue as unrelated.

Thanks again,

**Comment by xomachine** [comment]
I think they are related to my compiler version (0.18.0). E.g.:
```
swayipc.nim(272, 21) Error: undeclared identifier: 'BitsRange'
swayipc.nim(272, 30) Error: no generic parameters allowed for BitsRange
swayipc.nim(272, 30) Error: no generic parameters allowed for BitsRange
swayipc.nim(289, 52) template/generic instantiation from here
swayipc.nim(300, 18) Error: type mismatch: got <AsyncSocket, string>
but expected one of: 
proc connectUnix(socket: Socket; path: string)
  first type mismatch at position: 1
  required type: Socket
  but expression 'sock' is of type: AsyncSocket
```
