### ISSUE TITLE
Custom size and sizeof for sequences not working

### ISSUE THREAD

**Issue by oswjk** [xomachine/NESM#7]
This snippet:

```nim
import nesm

serializable:
    type MyType = object
        kind: byte
        size: uint32
        data: seq[byte] as {size: {}.size}
```

Generates the following when compiling with `nim c -d:debug foo.nim`:

```nim
proc deserialize(a167008: typedesc[MyType]; thestream: Stream): MyType =
  discard
  assert(1 ==
      thestream.readData(result.kind.unsafeAddr, 1),
         "Stream was not provided enough data")
  assert(4 ==
      thestream.readData(result.size.unsafeAddr, 4),
         "Stream was not provided enough data")
  result.data = newSeq[byte](result.size)
  var length167004: int32
  assert(4 ==
      thestream.readData(length167004.unsafeAddr, 4),
         "Stream was not provided enough data")
  result.data = newSeq[byte](length167004)
  if result.data.len() > 0:
    assert(result.data.len() * 1 ==
        thestream.readData(result.data[0].unsafeAddr, result.data.len() *
        1), "Stream was not provided enough data")
```

So the code reads the size field as it should and uses it to allocate a sequence. But it also reads another size and allocates the sequence a second time. This second length is probably what is generated when not having the custom size specified and in this case it's not wanted because the length is read from the user specified field.

I tried this with latest (devel) Nim and installed nesm with nimble.

**Comment by xomachine** [comment]
The fix is here, but I will merge it to the master after some refactoring of the {size} option code. There was a bit of mess in tests and relying on the unstable compiler behavior.
